export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAILURE = "ALL_PRODUCT_FAILURE";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";

export const PRODUCT_DETAILS_REQUEST = "ALL_DETAILS_REQUEST ";
export const PRODUCT_DETAILS_SUCCESS = "ALL_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILURE = "ALL_DETAILS_FAILURE";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAILURE = "NEW_REVIEW_FAILURE";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
