export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAILURE = "ALL_PRODUCT_FAILURE";

export const PRODUCT_DETAILS_REQUEST = "ALL_DETAILS_REQUEST ";
export const PRODUCT_DETAILS_SUCCESS = "ALL_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILURE = "ALL_DETAILS_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
